services:
 
  postgres:
    image: postgres
    container_name: postgresdb
    environment:
      POSTGRES_USER: mariliadb
      POSTGRES_PASSWORD: passworddb
      POSTGRES_DB: nestdb
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: nest-api
    env_file: .env
    ports:
      - '${API_PORT}:${API_PORT}'
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://mariliadb:passworddb@postgres:5432/nestdb
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
    command: sh -c "npx prisma migrate deploy && npm run start:prod"
